### PR TITLE
updated IsTerminal in order to be compatible with upstream changes

### PR DESCRIPTION
**Pull request by GregorioDiStefano**
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>

### CODE REVIEW

**Comment by GregorioDiStefano** [comment]
@kacf @bboozzoo I was no longer able to build my mender stress test client without this change

**Comment by bboozzoo** [comment]
does it break any other code?

**Comment by GregorioDiStefano** [comment]
I tried building the official client, and it worked. Haven't checked anything else.

**Review by ghost — APPROVED** [review]
Hmm, they changed their public API. It might require a vendor-update of mender, but otherwise should be good.

**Pull request merged**
